### ISSUE TITLE
Remove Bash dependencies

### ISSUE THREAD

**Issue by mhofman** [twilio/ortc-adapter#2]
For a package helping support Microsoft's browser, having a hard dependency on Make and Bash is a little strange.
Any chance to make this cross platform, i.e. run on Windows. I hear pure node runs everywhere ;)

**Comment by markandrus** [comment]
Oh my, you are right. I should change that.

**Comment by markandrus** [comment]
OK, I have replaced make with gulp in ddbf4753dd46e9739b1cb2af25e20b664a61a108. Just tried `npm install` on Windows and it worked. :-)
