### ISSUE TITLE
Thoughts on latest editor's draft

### ISSUE THREAD

**Issue by manvalls** [twilio/ortc-adapter#7]
As you can see [here](http://w3c.github.io/webrtc-pc/) it seems that `addStream` is going away in favour of `addTrack`. Will it go away from this adapter as well?

**Comment by markandrus** [comment]
@manvalls I will probably keep it so long as other browser-based WebRTC implementations keep it. Eventually it might be marked deprecated (or at least commented as such).

Are you concerned about it being removed or staying?

**Comment by manvalls** [comment]
I'd prefer it to stay of course.

**Comment by markandrus** [comment]
:+1: it will stay
